services:
  app:
    image: 'my-spring-boot-app'
    container_name: 'kninit-spring-boot-app-1'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - './src:/app/src'  # Synchronizacja kodu źródłowego
    restart: 'always'
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mydatabase'
    depends_on:
      - 'mongodb'

    command: ["./app/gradlew", "bootRun"]  # Upewnia się, że aplikacja startuje poprawnie

  mongodb:
    image: 'mongo:latest'
    container_name: 'kninit-mongodb-1'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
    restart: 'always'

volumes:
  mongodb_data:
